project:
  type: website
  resources:
    - "media/*"

website:
  title: "Colin Mast"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - teaching.qmd
      - field.qmd
      - publications.qmd
      - research.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

